spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mini_instagram_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    root: INFO
    com.nchuy099.mini_instagram: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE