spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/mini_instagram_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: none
      # naming:
      #   physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt:
  access:
    key: access-secret-key
    expireMins: 60      
  refresh:
    key: refresh-secret-key
    expireDays: 7     
  reset:
    key: reset-secret-key
    expireMins: 15        

logging:
  level:
    root: INFO
    com.nchuy099.mini_instagram: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE